# Generated by Django 3.0.5 on 2021-01-11 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('published', models.DateField(default=datetime.date(2021, 1, 11))),
            ],
        ),
    ]
